Trigger WF runs on PR
cookiejar/cookietemple pull request #530
Opened 2020-11-29 18:04 UTC by Imipenem

Run WF on push and pr

2020-11-29 18:47 UTC, Zethson commented on .github/workflows/create_cli_java.yml
> +  pull_request:
We should also ignore the paths here I guess. It brings CI runs down.

2020-11-29 18:48 UTC, Zethson commented on .github/workflows/create_cli_python.yml
> +  pull_request:
Apples here as well and to all other create workflows

2020-11-29 18:50 UTC, Zethson requested changes
I would add the ignore paths everywhere. Rest LGTM

2020-11-30 07:39 UTC, Imipenem commented
I will fix this asap

2020-12-01 18:45 UTC, Imipenem commented
@Zethson : There are issues with GitHub actions according to GitHub Status page, so I suggest wait for them to be resolved before merging!

2020-12-02 10:43 UTC, Zethson approved these changes
LGTM

2020-12-02 11:01 UTC, merged